#ifndef CASTLING_PERMISSIONS   /* Include guard */
#define CASTLING_PERMISSIONS

#define NO_CASTLING  0
#define WHITE_KINGSIDE_CASTLE 1
#define WHITE_QUEENSIDE_CASTLE 2
#define BLACK_KINGSIDE_CASTLE 4
#define BLACK_QUEENSIDE_CASTLE 8

#endif